### ISSUE TITLE
Should the game support intangibility?

### ISSUE THREAD

**Issue by macsforme** [TeamChillax/design#4]
Taken from @JeffM2501's original document:

Do we want to allow players to pass through world geometry? The only reason we need to make this choice is so our design can include features to allow it. If we allow it, we'll need to come up with some graphical effect to show it, and decide how we want to handle ambiguous cases in world geometry (preventing players from phasing through the floor, for instance).

**Comment by macsforme** [comment]
I don't have strong feelings for or against this proposal. In BZFlag, this feature did contribute some interesting variety to the game as well as a rather cool (for its time) graphical effect. On the other hand, there were edge cases to deal with, such as when players were at the extreme edge of an object and they were unable to fire, or when they lost their flag (by having it stolen by Thief, or through some kind of glitch) and got stuck in between the interior and exterior. For drive-through buildings, there was also no automatic visual distinction between those and standard objects, which created some confusion.

I feel like this feature could benefit the game on the whole, but I would want a suitable visual effect when traversing an object via powerup, as well as a visual distinction between standard objects and drive-through objects.

**Comment by JeffM2501** [comment]
Shaders can be used to slice arbitrary meshes at some clipping plane and fill that with something graphical, but it will require work. I could easaly see finding a graphical effect delaying the project as a whole.

Like moving objects, I'd focus on the game with out it and see if we need to add it later. in bzflag it is mostly a minor powerup and does not really "define" the game style like other things.

**Comment by allejo** [comment]
> as well as a visual distinction between standard objects and drive-through objects.

Some puzzle maps take advantage of having objects blend-in to allow for hidden. Whether there is some differentiation between them by default or not, there should be a way to override this with textures or materials.

How will "one-way" walls work for meshes? Will this affect that?

**Comment by JeffM2501** [comment]
The "one way" wall effect of bzflag is not actually a design feature, it's a bug that turned out to be fun. The game only did collisions if the motion vector and the surface normal of the collision were in opposite directions. When you get behind a non-manifold shape, the vectors are aligned so it doesn't check for collisions on the backside of the face.

If we go with a modern physics library it's going to want manifold volumes to work correctly. I think that passiblity should be a property of the shapes/faces/volumes(whatever) that are specifically defined by the engine. Then one way is just a specific property that always has the same defined behavior, not one that happens to work based on a specific collision detection implementation.

I would keep the collision properties as completely separate from the visibility properties, so that map makers could combine them as needed for whatever desired effects.

**Comment by macsforme** [comment]
We could add a feature to the teleporter to allow for one-way portals. I don't think we want to rely on BZFlag's behavior for that. I'm not even sure I would want to support arbitrary triangle meshes in our worlds, as there would be numerous complications if we did so (physics considerations, editor support without creating a full-blown modeler, determining what points are "inside" the object, etc.). Intangible objects might be a lot easier to do if we have pre-defined object types (like BZFlag 1.x objects), rather than arbitrary meshes.

**Comment by JeffM2501** [comment]
The passability comments mentioned here will be taken into account, but the initial plan is to not allow an "OO" style power up in the initial implementation.
